u=float(input("Enter the x-cordinate for G "))
v=float(input("Enter the y-coordinate for G "))
w=float(input("Enter the direction in degrees for G "))

x=float(input("Enter the x-cordinate for B "))
y=float(input("Enter the y-coordinate for B "))
z=float(input("Enter the direction in degrees for B "))

i=float(input("Enter the x-cordinate for A "))
j=float(input("Enter the y-coordinate for A "))
k=float(input("Enter the direction in degrees for A "))

import turtle
def draw_G(gal):
    gal.penup()
    gal.setx(u)
    gal.sety(v)
    gal.setheading(w)
    gal.pendown()
    gal.fd(50)
    gal.rt(90)
    gal.fd(50)
    gal.rt(90)
    gal.fd(75)
    gal.rt(45)
    gal.fd((1250)**(1/2))
    gal.rt(45)
    gal.fd(50)
    gal.rt(45)
    gal.fd((1250)**(1/2))
    gal.rt(45)
    gal.fd(75)
    gal.ht()
    return

def draw_B(gal):
    gal.penup()
    gal.setx(x)
    gal.sety(y)
    gal.setheading(z)
    gal.pendown()
    gal.fd(50)
    gal.rt(45)
    gal.fd((1250)**(1/2))
    gal.rt(45)
    gal.fd(50)
    gal.rt(45)
    gal.fd((1250)**(1/2))
    gal.rt(45)
    gal.fd(50)
    gal.rt(90)
    gal.fd(100)
    gal.up()
    gal.rt(90)
    gal.fd(75)
    gal.rt(90)
    gal.fd(50)
    gal.down()
    gal.rt(90)
    gal.fd(75)
    gal.ht()
    return

def draw_A(gal):
    gal.penup()
    gal.setx(i)
    gal.sety(j)
    gal.setheading(k)
    gal.pendown()
    gal.rt(240)
    gal.fd(((10000/3)+10000)**(1/2))
    gal.rt(240)
    gal.fd(((10000/3)+10000)**(1/2))
    gal.rt(180)
    gal.penup()
    gal.fd((((10000/3)+10000)**(1/2))/2)
    gal.pendown()
    gal.rt(60)
    gal.fd(60)
    gal.ht()
    return
marker = turtle.Turtle()
draw_B(marker)
draw_A(marker)
draw_G(marker)
window = turtle.Screen()
window.mainloop()